apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: virtink
build:
  local:
    useBuildkit: true
  artifacts:
    - image: virt-controller
      docker:
        dockerfile: build/virt-controller/Dockerfile
      requires:
        - image: virt-prerunner
          alias: PRERUNNER_IMAGE
    - image: virt-daemon
      docker:
        dockerfile: build/virt-daemon/Dockerfile
    - image: virt-prerunner
      docker:
        dockerfile: build/virt-prerunner/Dockerfile
deploy:
  helm:
    releases:
      - name: virtink
        namespace: virtink-system
        chartPath: ./deploy/helm/virtink
        artifactOverrides:
          virtController.image: virt-controller
          virtDaemon.image: virt-daemon
        imageStrategy:
          helm:
            explicitRegistry: true
