apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: virt-daemon
  namespace: virtink-system
spec:
  selector:
    matchLabels:
      name: virt-daemon
  template:
    metadata:
      labels:
        name: virt-daemon
    spec:
      serviceAccountName: virt-daemon
      containers:
        - name: virt-daemon
          image: virt-daemon
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - --zap-time-encoding=iso8601
          volumeMounts:
            - name: kubelet-pods
              mountPath: /var/lib/kubelet/pods
      volumes:
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
