---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: virt-controller
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/virt-controller-cert
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: virt-controller
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-virtualmachine
  failurePolicy: Fail
  name: mutate.virtualmachine.v1alpha1.virt.virtink.smartx.com
  rules:
  - apiGroups:
    - virt.virtink.smartx.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: virt-controller
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/virt-controller-cert
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: virt-controller
      namespace: {{ .Release.Namespace }}
      path: /validate-v1alpha1-virtualmachine
  failurePolicy: Fail
  name: validate.virtualmachine.v1alpha1.virt.virtink.smartx.com
  rules:
  - apiGroups:
    - virt.virtink.smartx.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: virt-controller
      namespace: {{ .Release.Namespace }}
      path: /validate-v1alpha1-virtualmachinemigration
  failurePolicy: Fail
  name: validate.virtualmachinemigration.v1alpha1.virt.virtink.smartx.com
  rules:
  - apiGroups:
    - virt.virtink.smartx.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinemigrations
  sideEffects: None
