{{- $service := .Values.virtDaemon }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    {{- include "virtink.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $service.name }}
spec:
  selector:
    {{- include "virtink.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $service.name }}
  ports:
    - port: 443
      targetPort: 9443
