// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/smartxworks/virtink/pkg/daemon (interfaces: RelayProvider)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	tls "crypto/tls"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRelayProvider is a mock of RelayProvider interface.
type MockRelayProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRelayProviderMockRecorder
}

// MockRelayProviderMockRecorder is the mock recorder for MockRelayProvider.
type MockRelayProviderMockRecorder struct {
	mock *MockRelayProvider
}

// NewMockRelayProvider creates a new mock instance.
func NewMockRelayProvider(ctrl *gomock.Controller) *MockRelayProvider {
	mock := &MockRelayProvider{ctrl: ctrl}
	mock.recorder = &MockRelayProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayProvider) EXPECT() *MockRelayProviderMockRecorder {
	return m.recorder
}

// RelaySocketToTCP mocks base method.
func (m *MockRelayProvider) RelaySocketToTCP(arg0 context.Context, arg1, arg2 string, arg3 *tls.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelaySocketToTCP", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RelaySocketToTCP indicates an expected call of RelaySocketToTCP.
func (mr *MockRelayProviderMockRecorder) RelaySocketToTCP(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelaySocketToTCP", reflect.TypeOf((*MockRelayProvider)(nil).RelaySocketToTCP), arg0, arg1, arg2, arg3)
}

// RelayTCPToSocket mocks base method.
func (m *MockRelayProvider) RelayTCPToSocket(arg0 context.Context, arg1 string, arg2 *tls.Config, arg3 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelayTCPToSocket", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelayTCPToSocket indicates an expected call of RelayTCPToSocket.
func (mr *MockRelayProviderMockRecorder) RelayTCPToSocket(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelayTCPToSocket", reflect.TypeOf((*MockRelayProvider)(nil).RelayTCPToSocket), arg0, arg1, arg2, arg3)
}
