apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: virt-controller-cert
  namespace: virtink-system
spec:
  issuerRef:
    kind: Issuer
    name: virt-controller-cert-issuer
  dnsNames:
    - virt-controller.virtink-system.svc
    - virt-controller.virtink-system.svc.cluster.local
  secretName: virt-controller-cert
