apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lockspace-attacher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lockspace-attacher
subjects:
  - kind: ServiceAccount
    name: lockspace-attacher
    namespace: virtink-system
