{{- $service := .Values.virtDaemon }}
{{- $image := merge $service.image .Values.image }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $service.name }}
  labels:
    app.kubernetes.io/component: {{ $service.name }}
spec:
  selector:
    matchLabels:
      {{- include "virtink.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $service.name }}
  template:
    metadata:
      {{- with $service.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "virtink.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $service.name }}
    spec:
      serviceAccountName: {{ $service.name }}
      containers:
        - name: {{ $service.name }}
          image: {{ include "virtink.image" $image }}
          imagePullPolicy: {{ $image.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - --zap-time-encoding=iso8601
          volumeMounts:
            - name: kubelet-pods
              mountPath: /var/lib/kubelet/pods
            - name: cert
              mountPath: /var/lib/virtink/daemon/cert
              readOnly: true
      volumes:
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: cert
          secret:
            secretName: virt-daemon-cert
            defaultMode: 420
