name: e2e

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  e2e:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - run: make e2e
